name    'mdobrev-tomcat6'
version '0.4.4'
source 'https://github.com/mclueppers/puppet-tomcat6'
author 'mdobrev'
license 'Apache-2.0'
summary 'A tomcat6 module that supports multiple instances'
description 'A tomcat6 module that supports multiple instances'
project_page 'https://github.com/mclueppers/puppet-tomcat6'
dependency 'puppetlabs/stdlib', '>= 2.6.0'
